### ISSUE TITLE
Support for AMD define(function () { }); form

### ISSUE THREAD

**Issue by jrburke** [weepy/brequire#3]
This came up in this [pull request for CoffeeScript](https://github.com/jashkenas/coffee-script/pull/1826), where brequire may not be able to handle this form:

```javascript
    define(function () { });
```

I am a bit unclear on the part that fails for brequire -- it looks like brequire is used to generate a transport form of CommonJS modules for use in the browser. So is the concern that the transform step does not find these anonymous define calls or that brequire uses AMD in the browser wrapping code, and cannot process the anonymous require calls?

A bundling tool for AMD libraries will need to name the anonymous define calls when bundling up the libraries.

**Comment by weepy** [comment]
closing since AMD seems to have fallen out of favour
